# Conexión a MongoDB Atlas para la API de Discografía
spring.data.mongodb.uri=mongodb+srv://franciscohuaiquicheo89_db_user:francisco89@eva-u3-express.xxxx.mongodb.net/discografia_db?retryWrites=true&w=majority
spring.data.mongodb.database=discografia_db

# Configuración del servidor
server.port=8080